lightninglabs/loop

- README.md
Add in the name of the command to loop out at the top
> README: Add loop out name

- README.md
I missed this cause I am a dummy and just assumed my lnd install was okay.
> README: Bold text lnd install instruction for dummies

- cmd/loop/main.go
Issue https://github.com/lightninglabs/loop/issues/28
> Change loopd global option parameter to rpcserver

- cmd/loop/loopout.go
Add the option to use an argument when specifying the amount
> cmd/loop: add amount as a discrete argument

- README.md
- cmd/loopd/config.go
- cmd/loopd/daemon.go
> cmd/loopd: point to testnet loop server for testnet mode

- README.md
Modify description of Loop In to indicate it is supported on testnet
> Update to reflect testnet is supported

- README.md
Add a note that you can use 0.6.0 to use Loop
> Update documentation for 0.6.0 release

- cmd/loop/main.go
Reduce the maximum routing fee rate to more expected levels of fee rate
> cmd/loop: reduce off-chain payment max-fee

- version.go
Bump the version number to the next release number
> version: bump version to 0.1.3

- lndclient/basic_client.go
This is useful for lndmon's usage of loop's lndclient package so we can restrict lndmon to `readonly.macaroon` rather than `admin.macaroon`.
> lndclient/basic_client: pass full macaroon path, not just directory.

- README.md
Fixes https://github.com/lightningnetwork/lnd/issues/3193
> README: Add routerrpc sub-server tag

- version.go
Bump the version number to the next release number
> version: bump version to 2.0.1

- loopout.go
- swap/fees.go
Right now, the loop client trusts that the loop server responds with a correct swap invoice.  This makes it possible for a loop server to respond with a regular(non-hold) invoice whose hash is generated by the server, and the client would still pay it.
To prevent this from happening, this PR makes the client check that the hash of the swap invoice is the same as the hash it generated. If the hashes are not equal, the client returns an error and aborts the swap.
>  loop+loopout: validate hash of swap invoice

- client.go
- loopin.go
- loopout.go
- sweep/sweeper.go
> multi: base sweep fee estimate on actually used address type

- version.go
Bump the version number to the next release number
> version: bump version to 0.2.2

- version.go
Bump the version number to a new patch release version
> version: bump version to 0.2.4

- README.md
Replace non-working slack link with working link
> readme: update slack link

- version.go
Bump version for release of time delayed Loop Out
> version: bump version to 0.3.0

- lsat/caveat.go
- lsat/caveat_test.go
- lsat/identifier.go
- lsat/identifier_test.go
- lsat/satisfier.go
- lsat/service.go
- lsat/service_test.go
We introduce a new package: `lsat`, which aims to provide utilities that will serve useful in the context of LSAT creation and verification for LSAT-enabled services.
> lsat: introduce LSAT related utilities

- go.mod
- go.sum
- loopin.go
A field changed from satoshis to msat, so we must do the conversion.
> [trivial] dep+looping: update to latest lnd master

- lsat/identifier.go
Add an explicit type for the token ID.
> lsat: add token ID type

- version.go
Bump version for release of time delay quote support
> version: bump version to 0.3.1

- client_test.go
- loopin.go
- loopin_test.go
- loopout_test.go
- test/lnd_services_mock.go
- test/signer_mock.go
> loopin: fix handling of incorrect amount in external htlc tx

- loopd/config.go
Point to the new LSAT enabled server backend.
> loopd: add LSAT enabled server ports

- lndclient/router_client.go
Prepare for loop in last hop selection.
> lndclient: add last hop restriction

- version.go
> version: bump version to 0.4.1-beta

- test/chainnotifier_mock.go
This is the remainder of the previous PR (https://github.com/lightninglabs/loop/pull/174) which was left out by my mistake. This is required to make it fully possible to test scenarios where we're watching the chain for different versions of the same transaction (eg. NP2WSH and P2WSH)
> test: followup update chainnotifier mock to fwd notifications for matching txs

- go.mod
- go.sum
- lndclient/router_client.go
Otherwise mpp isn't supported.
> lndclient: move to V2 payment methods

- lndclient/router_client.go
Required for a dependent project to get access to the failure reason of failed payments.
> lndclient: expose failure reason

- version.go
> version: bump version to 0.6.0-beta

- loopd/utils.go
One pass through of the max parts configuration value was forgotten in #185.
> loopd: fix setting of max parts

- version.go
Increment version number for a new release
> version: bump to v0.6.3-beta

- cmd/loopd/main.go
> cmd/loop: set exit code 1 on error

- go.mod
- go.sum
- looprpc/client.pb.go
- looprpc/client.pb.gw.go
- looprpc/client.proto
- looprpc/client.swagger.json
- looprpc/server.pb.go
Fixes https://github.com/lightninglabs/loop/issues/164
> looprpc: fix doc on routing fee units

- loopd/swapclient_server.go
Probably introduced https://github.com/lightninglabs/loop/pull/184
> loopd: return missing p2wsh loop out address

- lndclient/basic_client.go
Used to allow sub-server interaction using the basic connection.
> lndclient: extract basic connection

- README.md
update Slack link to redirection link
> docs: Update Slack link

- looprpc/client.pb.go
- looprpc/client.proto
- looprpc/client.swagger.json
From your grammar nazi with love
> looprpc/docs: fix typo

- version.go
> version: bump to v0.7.0-beta

- loopout.go
Allow for more time to search for low-routing fee pathways to the Loop service
> loopout: Increase payment timeout

- client.go
- loopd/view.go
- loopin.go
- loopin_test.go
- loopout.go
- swap.go
- swap/htlc.go
- swap/htlc_test.go
- sweep/sweeper.go
This PR lays the ground work for integrating the v2 HTLC script by adding support to for using it in the `swap` module.
> preliminary work for integrating the v2 HTLC script

- version.go
> version: bump to 0.8.1-beta

- version.go
Increment version for new features
> version: bump to 0.9.0-beta

- release_notes.md
Forgot to add the release notes for the macaroons in #281.
> release_notes: add macaroons

- release_notes.md
- version.go
> version: bump to 0.10.0-beta

- README.md
- docs/autoloop.md
> docs: add autoloop documentation

- release_notes.md
- version.go
> version: bump to 0.11.1-beta

- release_notes.md
- version.go
> version: bump to 0.11.2-beta

- go.mod
- go.sum
- liquidity/liquidity.go
- loopd/macaroons.go
- release_notes.md
- swap_server_client.go
This is mainly necessary as a preparation to bundle the final `lnd v0.12.0-beta` together with Loop inside of LiT.
> Bump lnd dependency to v0.12.0-beta.rc3

- release_notes.md
- version.go
> version: bump to 0.11.3-beta

- loopd/config.go
- release_notes.md
Fixes: https://github.com/lightninglabs/loop/issues/336
> loop: add sane default for --lnd.macaroonpath

- release_notes.md
- version.go
> version: bump to 0.11.4-beta

- cmd/loop/loopout.go
> loop: fix typo in htlc confs

- release_notes.md
- version.go
> version: bump to v0.12.0-beta

- README.md
- docs/faqs.md
A bunch of edits to better promote Autoloop and make Loop a bit more approachable to users. Ideally this lowers the barrier to entry for people wanting to get started
> Simplify the README

- release_notes.md
- version.go
> version: bump to v0.12.2-beta

- release_notes.md
- version.go
> version: bump version to v0.14.0-beta

- release_notes.md
- version.go
> version: bump version to v0.14.1-beta

- release_notes.md
- version.go
> version: bump version to v0.14.2-beta

- release_notes.md
- version.go
> version: bump version to v0.15.0-beta

- regtest/docker-compose.yml
partial fix for https://github.com/lightninglabs/loop/issues/429
> bump lnd versions from 12.1-beta to 13.4-beta

- loopd/daemon.go
- loopd/run.go
- loopd/view.go
Exporting creations of default listener config makes it easier to run loopd as a package.
> loopd: export NewListenerConfig

- release_notes.md
- version.go
Bump version number for release
> version: bump version to v0.16.0-beta

- release_notes.md
- version.go
> version: bump version to v0.17.0-beta

- loopout.go
I don't consider this a major feature, I hope you agree.
> loopout: remove double space in log message

- release_notes.md
> version: bump version to v0.19.1-beta

- release_notes.md
- version.go
> version: bump version to v0.20.0-beta

- version.go
> version: bump version to v0.20.1-beta

- release_notes.md
- version.go
> version: bump version to v0.20.2-beta

- release_notes.md
- version.go
> version: bump version to v0.21.0-beta

- release_notes.md
- version.go
> version: bump version to v0.22.0-beta

- Dockerfile
> build: bump golang version in the main Dockerfile

- version.go
> version: bump version to v0.22.1-beta

- release_notes.md
- version.go
> version: bump version to v0.23.0-beta

- swap/keychain.go
This PR decides on the actual key family value.
> swap: decide on actual keyfamily value

- looprpc/client.pb.gw.go
- looprpc/client.swagger.json
- looprpc/client.yaml
This PR aims to add entries to the REST documentation for the GetInfo rpc.
https://lightning.engineering/api-docs/api/loop/rest-endpoints/index.html
> looprpc: add rest entries for getinfo rpc

- version.go
> version: bump version to v0.24.1-beta

- labels/labels.go
- liquidity/liquidity.go
- liquidity/loopin_builder.go
- liquidity/loopout_builder.go
Based on https://github.com/lightninglabs/loop/pull/590
This PR adds a new label for easy autoloops. This helps us identify which loops were dispatched from easy-autoloop through the `user_agent` field
> Autoloop easy tag

- loopin.go
Fix some typos in  `loopin.go`.
> loopin: fix typos

- release_notes.md
- version.go
> version: bump version to v0.25.0-beta

- version.go
> version: bump version to v0.25.1-beta

- release.sh
Synchronize the release script with https://pkg.go.dev/modernc.org/sqlite#hdr-Supported_platforms_and_architectures
> build: remove unsupported platforms from the release script

- version.go
> version: bump version to v0.25.2-beta

- release_notes.md
Update xpub service release notes.
> docs: update release notes

- release_notes.md
- version.go
> version: bump version to v0.26.0-beta

- version.go
> version: bump to v0.26.1-beta

- version.go
> version: bump version to v0.26.3-beta

- version.go
> version: bump version to v0.26.4-beta

- version.go
bump version for leap year fix
> version: bump version to v0.26.5-beta

- executor.go
- loopd/daemon.go
- loopd/swapclient_server.go
This PR addresses some minor issues.
> Minor fixes

- version.go
> version: bump version to v0.26.6-beta

- release_notes.md
- version.go
> version: bump version to v0.27.0-beta

- instantout/manager.go
> instantout: fix swapserverrpc dependent compilation

- loopd/utils.go
Some minor clean up in the utils.
> Minor clean up in utils

- loopdb/sqlite.go
Potential fix for https://github.com/lightninglabs/loop/issues/706
> loopdb: make sqlite sync for extra durability

- loopout.go
> loop: fill the correct HTLC in loopout update

- loopout.go
Fixes https://github.com/lightninglabs/loop/issues/722.
> Send loop out prepay over selected outgoing chan set

- staticaddr/deposit/deposit.go
- staticaddr/deposit/fsm.go
- staticaddr/deposit/sql_store.go
This PR exposes deposit methods to other static address packages.
> StaticAddr: public scope for deposit methods

- regtest/docker-compose.yml
Fixes https://github.com/lightninglabs/loop/issues/746
> regtest: fix loopserver address

- staticaddr/version/protocol_version.go
This PR introduces a separate package for the static address protocol version to avoid cyclic imports in follow-up PRs.
> staticaddr: protocol version package

- release_notes.md
- version.go
> version: bump version to v0.28.2-beta

- liquidity/autoloop_testcontext_test.go
This failure became normal recently:
```
=== RUN   TestAutoLoopInEnabled
autoloop_testcontext_test.go:318:
Error Trace:	/home/runner/work/loop/loop/liquidity/autoloop_testcontext_test.go:318
/home/runner/work/loop/loop/liquidity/autoloop_test.go:804
Error:      	Not equal:
expected: 80000
actual  : 160000
Test:       	TestAutoLoopInEnabled
autoloop_testcontext_test.go:318:
Error Trace:	/home/runner/work/loop/loop/liquidity/autoloop_testcontext_test.go:318
/home/runner/work/loop/loop/liquidity/autoloop_test.go:804
Error:      	Not equal:
expected: 160000
actual  : 80000
Test:       	TestAutoLoopInEnabled
autoloop_testcontext_test.go:343:
Error Trace:	/home/runner/work/loop/loop/liquidity/autoloop_testcontext_test.go:343
/home/runner/work/loop/loop/liquidity/autoloop_test.go:804
Error: …
```
> liquidity: fix flaky autoloop test

- go.mod
- go.sum
This is the same as v0.18.0-beta.
> go.mod: update LND to v0.18.0-beta.1

- cost_migration.go
- loopd/daemon.go
- test/lightning_client_mock.go
> loop: paginate fetching payments when running the cost migration

- sweepbatcher/sweep_batch.go
- sweepbatcher/sweep_batcher_test.go
The race was detected in CI and locally when running with `-race`. It happened between the following calls:
```
WARNING: DATA RACE
Write at 0x00c0003e6638 by goroutine 1374:
runtime.racewrite()
<autogenerated>:1 +0x1e
github.com/lightninglabs/loop/sweepbatcher.(*batch).Wait()
sweepbatcher/sweep_batch.go:463 +0x6e
github.com/lightninglabs/loop/sweepbatcher.(*Batcher).Run.func1()
sweepbatcher/sweep_batcher.go:272 +0x10e
Previous read at 0x00c0003e6638 by goroutine 1388:
runtime.raceread()
<autogenerated>:1 +0x1e
github.com/lightninglabs/loop/sweepbatcher.(*batch).monitorConfirmations()
sweepbatcher/sweep_batch.go:1144 +0x285
github.com/lightninglabs/loop/sweepbatcher.(*batch).handleSpend()
sweepbatcher/sweep_batch.go:1309 +0x10e4
github.com/lightninglabs/loop/sweepbatcher.(*batch).Run() …
```
> sweepbatcher: fix race condition when stopping

- sweepbatcher/sweep_batch.go
- sweepbatcher/sweep_batcher.go
- sweepbatcher/sweep_batcher_test.go
In this PR I'm adding option WithCustomSignMuSig2 which provides another way of producing musig2 signatures.
> sweepbatcher: add option WithCustomSignMuSig2 

- interface.go
- liquidity/autoloop_testcontext_test.go
> chore: fix some comments for struct field

- sweepbatcher/store.go
- sweepbatcher/sweep_batcher.go
> chore: fix some comments

- sweepbatcher/sweep_batch.go
- sweepbatcher/sweep_batcher.go
- sweepbatcher/sweep_batcher_test.go
Previously sweepbatcher used `loop/labels.LoopOutBatchSweepSuccess` to assign transactions labels. The value is "BatchOutSweepSuccess -- $batch_id", which does not fit use cases outside of loop-out. Now there is option `WithTxLabeler` which sets a function used to generate the label.
> sweepbatcher: customize transaction labels

- go.mod
> build: use tagged looprpc v1.0.0

- loopdb/store_mock.go
Fixes: https://github.com/lightninglabs/loop/actions/runs/10664367829/job/29555488931?pr=786#step:6:1474
> loopdb: properly lock store mock for concurrent access

- version.go
> version: bump version to v0.28.9-beta

- release.sh
> chore: remove redundant word in release.sh

- .github/workflows/main.yml
> github: update cache version from deprecated v1 to v4

- version.go
> version: bump version to v0.29.1-beta

- Dockerfile
- go.mod
- go.sum
> bump LND to 0.19.3
