- client.go
- cmd/loopd/daemon.go
- cmd/loopd/view.go
Reason for the crash was an unpopulated HtlcAddress field.
Fixes #37
> loopd: fix nil ptr derefence for monitor

- cmd/loopd/config.go
- cmd/loopd/daemon.go
- cmd/loopd/utils.go
- go.mod
- lndclient/chainnotifier_client.go
- lndclient/invoices_client.go
- lndclient/lightning_client.go
- lndclient/lnd_services.go
- lndclient/macaroon_pouch.go
- lndclient/signer_client.go
- lndclient/walletkit_client.go
In this PR, we add a new struct, the `macaroonPouch`. This struct bundles all the macaroons we need for each sub-server. Along the way, we also export the set of default* paths for lnd, and add a new set of variables that store the default file names of each of the macaroons for each sub-server.
The `WithMacaroonAuth` method on the `serializedMacaroon` type will allow us to attach a macaroon for each call rather than attaching it at the connection level. This slight change will allow us to use multiple macaroons over a single RPC connection, rather than a single global macaroon.
Before this PR, we used the `admin.macaroon` for everything which meant that users on older versions of `lnd` may not have all the capabilities on their existing macaroon that was added for some of the …
> lndclient+cmd/loopd: use unique macaroon per sub-server to avoid users having to delete admin.macaroon

- cmd/loopd/config.go
- cmd/loopd/daemon.go
- swap/htlc.go
This commit fixes the bug that caused running loopd on testnet to connect to the mainnet swap server.
In addition to that, a fix for generation of the display htlc addresses is included.
> loopd: use proper default swap server address

- DOCKER.md
- Dockerfile
Introduced docker integration:
* Added Dockerfile to build loopd and loop with no dependencies.
* Added instructions to build and run docker image.
There's no MAINTAINER tag in the Dockerfile (yet). I wasn't sure who to put. Much of the Dockerfile contents come from @Roasbeef's LND Dockerfile though.
I don't know if the tone of the instructions is OK. Any thoughts?
Fixes #43.
> Introduced docker integration

- lndclient/basic_client.go
- lndclient/lnd_services.go
In this commit, we increase the gRPC block size from 4MB to 50MB
for the lndclient basic client.
Recently, the output of `lncli describegraph` has hit the block size cap
due to the expansion of the mainnet graph. Without this attempts to
fetch the graph return an error of:
```
[lncli] rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4246753 vs. 4194304)
```
With this commit, we give ourselves some breathing room for the
loop lnd basic client.
I'd like to use the `lndclient` package in `lndmon`, hence this PR.
> lndclient: increase lightning gRPC block size to 50MB

- README.md
Thought this would be useful to surface, didn't see it linked anywhere else in the project.
> Add RPC docs & ports to README

- loopout.go
- loopout_test.go
- store_mock_test.go
- test/lnd_services_mock.go
- test/walletkit_mock.go
This addresses an issue where using a sweep confirmation target greater than the default would result in most cases not revealing the preimage due to the default confirmation target yielding a higher fee than the max miner fee backed by the confirmation target provided.
> loopout: compare delta from htlc expiry correctly

- .golangci.yml
- .travis.yml
- Makefile
- client.go
- cmd/loop/loopin.go
- cmd/loop/loopout.go
- cmd/loop/main.go
- cmd/loop/quote.go
- executor.go
- lndclient/invoices_client.go
- lndclient/log.go
- lndclient/router_client.go
- log.go
- loopdb/loopin.go
- loopdb/loopout.go
- loopin.go
- loopout_test.go
- server_mock_test.go
- store_mock_test.go
- sweep/sweeper.go
- test/log.go
- test/testutils.go
- test/timeout.go
- testcontext_test.go
Use the same configuration for linting as in lnd. The command `make lint` can now be run and linting is also run on Travis build.
I fixed the most obvious errors then locked the linter down to only report new issues, added after c859f0c1b87e490ec1d7dd7aa15eea0dbf8c3ef6.
> Add linter to makefile, lint on Travis build

- client.go
- cmd/loop/loopin.go
- cmd/loop/loopout.go
- cmd/loop/main.go
- cmd/loopd/swapclient_server.go
- interface.go
- log.go
- loopin.go
- loopout.go
- swap.go
- swap/log.go
- swap/type.go
- testcontext_test.go
If we also want to use the types defined in loop on the server, we currently need to pull in the root module with all its dependencies.
By extracting the types into their own module, we avoid pulling in dependent sub-modules like `looprpc` for example when using the types in the server code.
> loop+cmd: extract types into common module

- README.md
This PR helps to ensure users are setting up and running the patched version of lnd.
> Increased minimum required version of lnd to 0.7.1 in README.md.

- lndclient/lnd_services.go
This PR increases the gRPC max receive size from 50MiB to 200MiB.
This is needed to fix https://github.com/lightninglabs/lndmon/issues/48.
> lndclient: increase gRPC max message receive size to 200MiB

- go.sum
- lndclient/router_client.go
This PR extends the proxy `SendPayment` method with parameters to allowing payments without an invoice. This is intended to be used for prepay probes.
> lndclient: extend send payment parameters

- lndclient/invoices_client.go
- lndclient/lightning_client.go
- test/invoices_mock.go
- test/lightning_client_mock.go
A change in lnd where a field was converted from Sat to MSat wasn't correctly propagated to the `lndclient`. This PR fixes that.
> lndclient: fix Value/ValueMsat conversion problem

- lndclient/invoices_client.go
- lndclient/lightning_client.go
Backward compatibility was not addressed in #121.
> lndclient: use old value field for backward compatibility

- .gitignore
- cmd/loopd/main.go
- go.mod
- go.sum
- lndclient/basic_client.go
- lndclient/lnd_services.go
- loopd/config.go
- loopd/daemon.go
- loopd/log.go
- loopd/main.go
- loopd/start.go
- loopd/swapclient_server.go
- loopd/utils.go
- loopd/view.go
This PR lays the foundational work to allow `loopd` to be used as a library. 
It moves the logic currently residing in `cmd/loopd` into a new package `loopd`, and adds configuration options for custom gRPC listeners, allowing `loopd` to both accept incoming connections on custom listeners, and connecting to an `lnd` instance on a custom listener.¨
This is similar to what was done for `lnd` to allow it to be used with in-memory gRPC clients, paving the way for mobile support: https://github.com/lightningnetwork/lnd/pull/3282
> Create loopd package, allow custom listeners

- lsat/interceptor.go
- lsat/interceptor_test.go
To be compliant with RFC 7235 section 4.1 we change the format of the
WWW-Authenticate header field to double quoted and comma separated
fields.
> lsat: change WWW-Authenticate header format

- cmd/loop/loopout.go
Add a new command line option `max_swap_routing_fee` for specifying max swap routing fee.
Fixes #100
> Add option for max swap off-chain routing fee

- client.go
- loopd/config.go
- loopd/daemon.go
- loopd/utils.go
- loopd/view.go
- lsat/interceptor.go
- lsat/interceptor_test.go
- swap_server_client.go
As `loopd` will pay for LSAT auth tokens automatically, we need a way to validate/restrict the maximum amount we are willing to pay on the client side.
This PR adds two new configuration parameters to `loopd`:
```
--maxlsatcost=   Maximum cost in satoshis that loopd is going to pay for an LSAT
token automatically. Does not include routing fees. (default: 1000)
--maxlsatfee=    Maximum routing fee in satoshis that we are willing to pay while 
paying for an LSAT token. (default: 10)
```
> lsat: validate cost of auth token

- loopd/config.go
- loopd/daemon.go
Fixes #146 by adding the command line option `--corsorigin` that can either be left empty (no CORS), set to a specific domain or allow all origins with `*`.
> loopd: add option to configure CORS origin

- cmd/loop/quote.go
With the restriction in place, it is not possible to use the
`--conf_target` and `--fast` flag at the same time. To avoid similar
problems in the future, the check for the number of amounts is
removed completely.
> cmd/loop: remove number of flags restriction

- lndclient/signer_client.go
- test/signer_mock.go
This is required by an external project to populate the witness/signature script of an input belonging to the backing lnd wallet.
> lndclient: expose ComputeInputScript in SignerClient

- lsat/interceptor.go
- lsat/interceptor_test.go
- lsat/store_test.go
We add a new stream intercept method to our interceptor that can attach the LSAT to a stream as well as an unary call.
> lsat: add stream interceptor

- client.go
- cmd/loop/loopin.go
- cmd/loop/main.go
- cmd/loop/quote.go
- looprpc/client.pb.go
- looprpc/client.proto
- looprpc/client.swagger.json
Fixes #157.
The fee estimation in loop in works differently from loop out. Because a transaction has to be created that sends the exact amount of BTC to the HTLC, the fee estimation is done by lnd's wallet which tries to construct a real transaction. If not enough funds are available to construct such a sample transaction, the whole quote call would previously fail.
This PR partially fixes this by not failing the quote call but returning a fee of 0 instead. The command line will show a warning to the user in this case. Applications using the gRPC or REST interface should inform the user about the possible reasons if the miner fee shows 0.
> Don't fail loop in quote if balance is insufficient for the miner fee estimation

- cmd/loop/main.go
Increase rate maximum multiplier to increase maximum fees when there is a large fee rate change
> cmd/loop: bump rate maximum

- client.go
- loopd/config.go
- loopd/daemon.go
- loopd/utils.go
- swap_server_client.go
This allows Loop users to further improve their privacy by not revealing their source IP address. Note that the identity of the lnd node behind Loop can still be revealed when performing a Loop In due to the swap server extending an off-chain HTLC to the user.
Onion addresses don't yet exist for the swap servers, but they will be added at a later time.
> loopd: add SOCKS proxy config option to dial swap server over Tor

- loopd/swapclient_server.go
This PR adds a missing mutex unlock upon return and fixes a subtle race condition when the subscriber may still write to the concurrent queue but the concurrent queue is closed, which can block the write.
> loopd: add missing mutex unlock and fix subtle reace condition

- test/chainnotifier_mock.go
This PR implements support for multiple tx notification subscribers in the
chain notifier mock. This is needed to make it possible to test scenarios
where we're watching the chain for different versions of the same transaction
(eg. NP2WSH and P2WSH)
> test: update chainnotifier mock to fwd notifications for matching txs

- README.md
- cmd/loop/loopin.go
- cmd/loop/loopout.go
- cmd/loop/main.go
Fixes #176.
Optimizes how the fees are displayed and called in the command line output and then documents them in the README.
> cmd/loop+README: explain fees and optimize fee display

- README.md
- client.go
- client_test.go
- lndclient/lnd_services.go
- lndclient/lnd_services_test.go
- lndclient/macaroon_pouch.go
- lndclient/versioner_client.go
- loopd/start.go
- test/lnd_services_mock.go
- test/versioner_mock.go
`lnd` version `v0.10.0` introduced some breaking API changes to the `routerrpc`. To detect this and fail gracefully, we rely on the new `GetVersion` RPC method of the `verrpc` subserver of `lnd` and pin every `loop` version to a compatible `lnd` version from now on.
This PR also assumes that the next version of the`loop` client release will be `v0.6.0`.
> Make loop aware of lnd's version

- client.go
- executor.go
- go.mod
- go.sum
- lndclient/router_client.go
- loopd/config.go
- loopd/utils.go
- loopout.go
- swap_server_client.go
As we are still in the experimentation phase with MPP, it is probably safer to expose this setting to the user. They can set it to `1` in case they don't want multi-loops.
A further step is to make `max_parts` a swap parameter that is passed in through the client rpc interface. This however also requires a database change. It therefore seems to be wiser to await how the current implementation of MPP will be received first.
> loopd: make maximum number of payment parts configurable

- .travis.yml
Overwrite travis's default of only cloning the last 50 commands so that travis can find the reference point for our linter.
Alternate is to shift reference point: #191
> traivs: set depth to false to clone whole repo

- loopd/swapclient_server.go
This PR fixes htlc addresses in LoopIn SwapResponse (issue: https://github.com/lightninglabs/loop/issues/197)
> loopin: fix htlc address in LoopIn SwapResponse

- version.go
We can't remove the previous tag, so need to bump again unfortunately.
Before next release, we need to improve the release scripts to add checks for all these things like we recently did for the lnd release script.
> version: bump to v0.6.2-beta

- Makefile
- release.sh
To prevent some common human errors when building a release. Changes taken from lnd release script, not invented here.
> release: add tag and version verification to release script

- lndclient/lightning_client.go
- lndclient/router_client.go
- test/lightning_client_mock.go
- test/lnd_services_mock.go
This PR adds `ListChannels` to `LightningClient` and extends `RouterClient.SendPayment` with keysend.
> lndclient: extend LightningClient with ListChannels and RouterClient with keysend

- cmd/loop/main.go
- cmd/loopd/main.go
- loopd/config.go
- loopd/daemon.go
- loopd/run.go
- loopd/start.go
- loopd/swapclient_server.go
- loopd/utils.go
- loopd/view.go
To be able to run loopd as a library, we need to export some config related elements and create the possibility to instantiate and run the RPC server without it creating its own grpc.Server server or REST proxy.ServeMux instance.
> loopd+config: prepare to be used as a library

- lndclient/lnd_services.go
In this commit, we now ensure that we set the max resp size for the
sub-server connection we create. Without this, it's possible that
several calls fail if the responses aren't yet paginated, or are very
large.
> lndclient: also set gRPC max resp size for sub-servers

- client.go
- loopd/config.go
- loopd/daemon.go
- loopd/utils.go
- swap_server_client.go
Config parameters can be confusing because `loopd` is both a client and a server. This PR adds a config section to isolate the loop server parameters.
Fixes #225
> loopd: group and clarify swap server parameters

- lndclient/lightning_client.go
- lndclient/walletkit_client.go
- test/lightning_client_mock.go
- test/lnd_services_mock.go
- test/walletkit_mock.go
Add additional fields and methods required to switch faraday over to lndclient, see lightninglabs/faraday/pull/46. 
This PR creates lndclient types for most of the rpc types, with the exception of `HtlcAttempt` (too many fields, felt like diminishing returns).
> lndclient: add methods required for faraday switchover

- loopdb/swapstate.go
Bug that can cause loop in swaps not to be resumed after a restart.
> loopdb: classify InvoiceSettled as pending

- loopdb/swapstate.go
- loopin.go
- loopin_test.go
- store_mock_test.go
Fix similar to https://github.com/lightninglabs/loop/pull/238 but for loop in.
Make sure we always keep tracking our own htlc, even if other htlcs are published on-chain.
Also adds a failure state for htlcs with an incorrect amount.
> loopin: record htlx tx hash

- loopd/config.go
- loopd/run.go
- loopd/utils.go
This PR adds config options which can be used to set a custom location for loopdb:
* `--datadir` allows setting of a custom database path without affecting where we put our logs
* `--loopdir` sets a single directory for logs, database and config, overwriting the other config values if they are present
We could probably achieve this with just `loopdir` but I included `datadir` just incase somebody has a use need to split logs and db.
Fixes #241
> loopd: allow custom database path

- loopd/config.go
- loopd/run.go
This PR fixes a regression introduced in #266 which removed the network path from the default location of our config file.
> loopd: add network to default config file path

- README.md
The links to the gRPC API as well as the REST API are broken. This PR fixes that.
> Fix grpc and rest api docs links

- loopout.go
Now that the server supports a longer CLTV maximum, the default sweep target may be increased to allow for lower on-chain costs
> loopout: Increase default sweep confirmation target

- release.sh
Go 1.15 removes support for darwin 386, so it should be removed from the release build target
> release: remove support for darwin 386

- Dockerfile
Building the docker image currently fails due to a module that requires a minimum golang version of 1.13.
> Upgrade docker image to golang 1.13

- .github/pull_request_template.md
- release_notes.md
- version.go
This PR adds a file to track release notes in-repo. 
Open to suggestions to how we do this, but I think an append-only log will work?
For our next client release we will have a list like this:
```
Feature 1
Feature 2
```
On release, we just shift the heading up:
```
Feature 1
Feature 2
```
And just keep doing that. Decided on "Next Release" because we don't always know whether a change will go into a point release or a major one.
> mutli: add release notes file to track in-repo

- loopd/config.go
With this PR we fix an issue where the macaroon path wasn't automatically expanded (turning `~/xyz/` into `/home/<user>/xyz`).
> config: expand macaroonpath flag

- go.mod
- go.sum
- loopd/macaroons.go
To make sure we can use the latest version of loop in LiT, we need to
make sure loop compiles against the actual v0.11.1 branch of lnd. There
were some conflicting changes to the macaroon service that didn't make
it to the branch that we need to roll back. Those changes don't affect
loop at all as we were always using the default root key ID anyway.
> mod+loopd: bump to lnd v0.11.1-beta.rc3

- loopd/macaroons.go
The macaroons PR #281 was merged shortly after the new suggestions endpoints, and does not include the permissions we need for these endpoints, making them unusable in master.
> loopd: add suggestions endpoints to macaroon permissions

- go.sum
`go mod tidy` (which our current modules check relies on) does not detect items that should be deleted in `go.sum`, this has recently been [addressed](https://github.com/golang/go/issues/33008) in go, so we can wait on the fix.  In the meantime, this PR cleans up our go.sum.
> go.sum: run go mod tidy to cleanup old dependencies

- release_notes.md
This PR moves the autoloop section of the release notes into the next release.
It also updates the instructions for the release to just clear everything that was there when we release, so that the notes are less ambiguous. These notes weren't really intended to replace the notes we add with tags, but rather to be a place where we can write updates, which can then be moved to the github tag and edited as we like once the release is ready.
Intended process is as follows:
- PRs include release notes under `Next Release`
- When it's time to release, bump the version and cut everything from `release_notes.md`
- Paste the release notes in the usual place
> releasenotes: move autoloop and simplify instructions

- README.md
Older versions of LND should not be used
> README: remove guidance for older versions of LND

- go.mod
- go.sum
To make it possible to remove the `replace` directive in LiT we update to the final `lnd` version.
> mod: update to final lnd version

- docs/autoloop.md
Update docs to note that our off chain and swap fees are percentages of volume.
> docs: update autoloop fees to explain fee percentages properly

- README.md
Additional notice for developers; they'll likely need HTTPS for connecting to exposed REST Api
> notes: update README.md

- Dockerfile
- release_notes.md
Using straight install does not set our current commit hash for
the daemon running in the docker container.
> dockerfile: use make rather than go install

- liquidity/liquidity.go
- liquidity/liquidity_test.go
- release_notes.md
This PR increases the confirmation target for automated loop out swaps and bumps our liquidity budget to use our new percentage based fee scheme.
> liquidity: update defaults budget and confirmation target

- loopd/swapclient_server.go
- loopd/swapclient_server_test.go
Fixes #57 
This commit adds verification to the loop out request to ensure that the
formatting of the specified destination address matches the network that
lnd is running on.
> loopd: verify that dest addr is for correct chain

- client.go
- config.go
- loopd/swapclient_server.go
- loopd/swapclient_server_test.go
This commit adds validation that checks if the loop out amount specified can
be satisfied given the nodes current channel balances. 
The total capacity is calculated as either the sum of the local balances of all active channels if no outgoing channel set is specified. Or if a set is specified then the total capacity is the sum of the local balances active channels in the specified set.
Fixes #104
> loopd: verify loop out amount

- README.md
- regtest/README.md
- regtest/docker-compose.yml
- regtest/regtest.sh
- release_notes.md
Fixes https://github.com/lightninglabs/loop/issues/276.
To help with development of apps that use the Loop daemon (`loopd`) for
liquidity management, it is often useful to test it in controlled environments
such as on the Bitcoin `regtest` network.
Lightning Labs provides a stripped down version of the Loop server that works
only for `regtest` and is only published in compiled, binary form (currently as
a Docker image).
The `docker-compose.yml` shows an example setup and is accompanied by a quick
start script that should make getting started very easy.
> docs+Docker: document how to use a regtest Loop server

- liquidity/interface.go
- liquidity/liquidity.go
- liquidity/liquidity_test.go
- release_notes.md
If we ran into a constraint while dispatching new autoloops (hit our in-flight limit or budget), we were not setting a disqualified reason, which would mean that this reasoning isn't surfaced to the user. This PR adds a test to demonstrate the bug and addresses it.
> autoloop: include peer rules for inflight/budget limits

- release_notes.md
- version.go
> version: bump to v0.12.1-beta

- loopd/daemon.go
- loopd/macaroons.go
- loopdb/store.go
- release_notes.md
To make sure we don't just block for forever if another Loop daemon
process is already running, we add a timeout and error out if obtaining
the unique file lock fails after 5 seconds.
> loopd+loopdb: add timeout to DB open

- executor.go
> loop: wait for chain notifier server to start

- loopout.go
- loopout_test.go
- test/lnd_services_mock.go
- test/walletkit_mock.go
If fees are too high for the client to reveal the preimage, and then suddenly drop as we reach our expiry, it is possible that the client reveals the preimage when we are undesirably close to the swap's expiry. This PR introduces a check that will abandon the swap if we are too close to expiry. This fee scenario is highly unlikely, but nonetheless we account for it just in case. It's important that we keep trying to sweep if the preimage has already been revealed (because the server can pull off-chain), so we only abandon swaps like this if we have not revealed the preimage yet. 
This PR introduces a check to ensure that we don't reveal our preimage too late, and adds a state that will indicate that the client chose not to reveal its preimage due to high fees. This will also cover the …
> loopout: do not reveal preimage too close to expiry

- docs/autoloop.md
I was reading Loop docs and I found a typo.
Minor change.
> docs: typo

- go.mod
- go.sum
- loopin.go
- loopin_test.go
- loopin_testcontext_test.go
In lnd 0.13 onwards, `SubscribeSingleInvoice` will terminate its stream once a final state is served (mirroring the behaviour of `TrackPayment`). 
* In regular cases where we're using the output of this stream, we are unaffected because we consume the final state then stop listening on the update channels. 
* When we're listening for invoice updates along with other cases (eg in `waitForSwapComplete` we're also waiting for the htlc spend to be confirmed) we need to handle the stream exit. 
This is mostly handled in lndclient, which closes the update channels, so this PR updates loop to use the new lndclient logic, and to test this functionality. We do a similar thing for loopout in `waitForHtlcSpendConfirmed`.
Depends on: lightninglabs/lndclient/pull/58
> loopin: handle SubscribeSingleInvoice termination

- loopd/config.go
- release_notes.md
There is an open issue for Python gRPC clients that is
currently being debugged grpc/grpc#23172
It can be mitigated server-side by specifying h2 in the metadata header.
> loopd: fix ALPN issue with Python

- client.go
- client_test.go
- loopin.go
- loopin_test.go
- loopout.go
- release_notes.md
Formatting our error was stifling any grpc error returned by the
server. Instead, we bubble up our grpc error, setting an unknown
code if the server did not specifically return an error code.
Fixes: #355
> multi: surface grpc error codes from server to client

- loopout_test.go
Running `go test -run=TestCustomSweepConfTarget` gives an error because the `CltvExpiry` is not set in the test.
This PR fixes it.
> loopout: fix TestCustomSweepConfTarget

- loopd/run.go
- release_notes.md
This makes two changes to handling of errors when configuration file
could not be loaded:
1. Only NotFound errors are considered OK - access errors and other FS
issues are now treated as fatal.
2. Failing to load config file specified explicitly via `--configfile`
option is alway a fatal error.
Rationale: If the configfile was specified explicitly then it indicates
the user really wishes to load it. While the user could want it to be
optionally loaded for extra configuration options, this can be
accomplished using an empty file.
If the config file was not specified explicitly then its' path was
computed from loop directory. If the file is inaccessible due to
permissions or other FS errors it's nearly certain other following
operations will fail as well. Failing early with a clear message …
> Improve error handling of config file

- loopd/daemon.go
- loopd/macaroons.go
Replaces #406.
In some cases we don't want the default macaroon file to be created on
disk, so we allow passing in a boolean that toggles the macaroon
creation.
This is for the LiT stateless integrated mode.
> Macaroon stateless

- cmd/loop/liquidity.go
- liquidity/autoloop_test.go
- liquidity/fees.go
- liquidity/interface.go
- liquidity/liquidity.go
- liquidity/liquidity_test.go
- liquidity/loopin.go
- liquidity/threshold_rule.go
- liquidity/threshold_rule_test.go
- loopd/swapclient_server.go
- looprpc/client.pb.go
- looprpc/client.proto
- looprpc/client.swagger.json
This PR does some preliminary work for adding autoloopin support. Primarily adding a swap type to our liquidity rules, and implementing some of the fees + budgeting plumbing we need.
> liquidity: add swap type and loop in fee logic

- cmd/loop/loopin.go
- cmd/loop/loopout.go
--allow-yes skips the confirmation prompt when performing loops. This is
super userful for scripts and negates the use of gnu yes
Fixes: 435
> main: add --force to loop in/loop out

- liquidity/liquidity_test.go
- loopdb/loopin.go
We already have a Label field in the embedded SwapContract
field for loop in swaps. This commit removes an erroneously
added Label field in LoopInContract which may be a cause of
ambiguity when referencing this field.
> multi: remove shadowed label variable in loopin swaps

- loopd/swapclient_server.go
- loopdb/protocol_version.go
- loopdb/protocol_version_test.go
- swap_server_client.go
The `looprpc` package is used for client and server protos, despite their being in different directories (`github.com/lightninglabs/loop/looprpc` and `github.com/lightninglabs/loop/swapserverrpc`). This is required to maintain backwards compatibility, because the package is used as part of the URI in grpc. 
[1] Use of mismatched package path/names (eg, import path `github.com/lightninglabs/loop/swapserverrpc` for `looprpc` package) causes issues when loop is imported as a package (as is the case in the server's itests) - the import can't be found. 
[2] Likewise, the presence of two `looprpc` packages (as is the case in `loopd/swapclient_server.go`) also confuses modules when we import `loopd` (to run `loopd` as a package, rather than a standalone binary in itests).
This PR updates loop to …
> multi: always alias swapserverrpc import for use as a package

- swapserverrpc/Dockerfile
- swapserverrpc/gen_protos.sh
- swapserverrpc/gen_protos_docker.sh
We don't need gprc-gateway for the client side copy of server protos.
> swapserverrpc: remove unnecessary vars in proto dockerfile

- client.go
- loopd/daemon.go
- loopd/macaroons.go
- release_notes.md
Found while debugging integration tests.
> loopd: close dbs when the daemon stops

- loopout.go
PR changes two things:
- We don't want to report routing results for prepays as those never use plugins. 
- If a plugin was requested but wasn't acquired then report result with the corrected label.
> loopout: do not report prepays and fix plugin type if acquire fails

- cmd/loop/liquidity.go
Previously, the feepercent flag on autoloop was set to an IntFlag and
later converted to Float, leading to the issue where users couldn't
specify decimal rates even though we allowed it.
> main: fix feepercent from intflags to float

- release_notes.md
- sweep/sweeper.go
Fixes #457.
The SignOutputRaw RPC is normally too lenient when it comes to fields
not being set, which is why this used to work previously. But with lnd
in remote signing mode, we need all the extra meta information available
on an input being signed for, so we actually need the pk script being
set.
Loop fully works with a remote signing lnd backend pair after applying
this fix.
> sweep: always send signed output's pk script

- release_notes.md
- version.go
> version: bump version to v0.18.0-beta

- Dockerfile
To support the same multiarch container build process that Pool introduced (https://github.com/lightninglabs/pool/pull/359).
> docker: add support for multiarch builds

- .github/workflows/docker.yml
Builds and pushes a Docker image for tags starting with `v`, e.g. `v1.2.3`
The image repository name is defined by environment variable `DOCKER_REPO`, which defaults to: `lightninglabs/loop`
To override it, if you want to publish the image to your own DockerHub account,
define a **Github Actions secret** named `DOCKER_REPO` with the full image repo name such as: `<docker_user>/loop`
> github: initial docker workflow

- loopd/swapclient_server.go
- loopd/swapclient_server_test.go
This PR adds a check to reject unsupported address formats such as P2PK (e.g. node pubkeys) or P2TR addresses
Should I add the fix to the `release_notes.md`?
references https://github.com/lightninglabs/lightning-terminal/issues/368
> loopout: reject P2PK addresses

- client.go
- client_test.go
- loopd/view.go
- loopin.go
- loopin_test.go
- loopout.go
- swap.go
- swap/htlc.go
- swap/htlc_test.go
- sweep/sweeper.go
This PR adds a few changes to the already existing taproot HTLC code to make it simpler to integrate.
- Refactor locking conditions.
- Derive the shared internal public key when creating the HTLC and export the root hash.
> multi: changes to the taproot HTLC  required for both client and server

- sweep/sweeper.go
This PR adds the sign method for the (currently unused) v3 htlc script spend case. This is a prerequisite for further changes and needs to be merged upstream before moving on with the remaining PRs. Originally this should have been included in https://github.com/lightninglabs/loop/pull/477.
> sweep: fill sign method when script spending a taproot htlc

- loopd/daemon.go
- loopd/macaroons.go
- loopd/perms/perms.go
This commit moves the RequiredPermissions map to its own directory so
that projects importing the permissions list dont need to import all the
dependencies of the loopd package.
> loopd: move RequiredPermissions to dedicated dir

- loopout.go
This PR adds more logging detail to the code paths where we publish sweeps and they fail at the chain backend side for any reason.
> loopout: log failed sweeps for more detail

- sweep/sweeper.go
This PR fixes sweeper fee estimation when sweeping to a taproot address.
> sweep: fix sweep fee estimation for p2tr outputs

- loopd/run.go
This commit bumps the minimum LND version to v0.15.4-beta which is needed to avoid chain sync issues caused by transactions with too large witnesses.
> loopd: bump minimum lnd version to v0.15.4

- client.go
- client_test.go
- loopd/swapclient_server_test.go
- loopd/view.go
- loopin.go
- loopin_test.go
- loopin_testcontext_test.go
- loopout.go
- loopout_test.go
- store_mock_test.go
- swap.go
- swap/htlc.go
- swap/htlc_test.go
- test/context.go
- test/testutils.go
- testcontext_test.go
This PR is a refactor of how we construct htlcs to make it possible to pass in internal keys for the sender and receiver when creating P2TR htlcs. Furthermore the commit also cleans up constructors to not pass in script versions and output types to make the code more readable.
> swap: refactor htlc construction to allow passing of internal keys

- .github/workflows/main.yml
- .golangci.yml
- client.go
- client_test.go
- cmd/loop/loopin.go
- executor.go
- interface.go
- loopdb/loop.go
- loopdb/meta.go
- loopin.go
- loopout.go
- loopout_test.go
- store_mock_test.go
- swap.go
- swap/htlc.go
- test/context.go
- test/lnd_services_mock.go
- testcontext_test.go
- tools/Dockerfile
This PR adds github actions to the ci. 
Compared to travis, the `rpc-check` check was added.
Tested it locally with `act`.
Travis could be removed in a further PR.
> ci: add github actions

- swap.go
Old swaps that did not have a protocol version could prevent loopd from starting when recreating their htlcs. This PR attempts to fix this issue.
> loop: correct htlc script version for very old swaps

- liquidity/fees.go
- liquidity/liquidity.go
- liquidity/liquidity_test.go
- liquidity/loopout.go
This PR removes the `PrepayAmount` from fee calculations for the `FeePortion` policy (percentage fee). This will allow smaller swaps to be dispatched and not get disqualified due to very high fees.
> liquidity: exclude prepay from total swap fees

- cmd/loop/info.go
- cmd/loop/main.go
- loopd/daemon.go
- loopd/perms/perms.go
- loopd/swapclient_server.go
- looprpc/client.pb.go
- looprpc/client.proto
- looprpc/client.swagger.json
- looprpc/client_grpc.pb.go
- looprpc/swapclient.pb.json.go
Implements https://github.com/lightninglabs/loop/issues/583.
This PR introduces a new `getInfo` RPC in `loopd`. Clients who call this new API should see  a list of basic `loopd` configuration parameters along with a summary of pending, succeeded and failed swaps. 
Here's an example with pending/succeeded loopins/loopouts:
```
{
"version": "0.23.0-beta commit=",
"network": "regtest",
"rpc_listen": "localhost:11010",
"rest_listen": "localhost:8081",
"macaroon_path": "/Users/xyz/Library/Application Support/Loop/regtest/loop.macaroon",
"tls_cert_path": "/Users/xyz/Library/Application Support/Loop/regtest/tls.cert",
"loop_out_stats": {
"pending_count": "1",
"success_count": "2",
"fail_count": "0",
"sum_pending_amt": "1000000",
"sum_succeeded_amt": "1500000"
},
"loop_in_stats": { …
```
> `getInfo` rpc for `loopd`

- docs/autoloop.md
The PR attempts to correct the documentation for `autobudgetrefreshperiod` to use a period instead of seconds.
Fixes: https://github.com/lightninglabs/loop/issues/592
> docs: correct `autobudgetrefreshperiod` example

- liquidity/interface.go
- liquidity/liquidity.go
- liquidity/liquidity_test.go
- liquidity/loopin_builder.go
- liquidity/loopin_builder_test.go
- liquidity/loopout_builder.go
- loopd/swapclient_server.go
Previously we would exclusively pass the autoloop boolean to multiple functions while they had directly access to the manager's parameters. With this commit we remove this explicit flag from the various function interfaces and retrieve the value directly from the parameters.
> NOTE: no changes in tests are required. Actually, we need to see all tests passing to verify that this diff didn't introduce any behavioral changes.
> liquidity: get autoloop flag directly from params

- liquidity/autoloop_test.go
After the FeePPM miner fee fix there has probably been a race condition in this test. The test would expect only one of the two quotes to work, as one had a marginally high miner fee. After the FeePPM fix that miner fee was considered valid and we dispatched two swaps instead of one, with the test setup examining the first one that reached the go channel.
> Autoloop-in flake fix

- docs/autoloop.md
- liquidity/autoloop_test.go
- liquidity/liquidity.go
Previously we would always use a hard-coded 20_000ppm swap fee for automatically dispatched swaps of easy autoloop. With this PR we will respect the `feepercent` parameter, if set.
> Easy autoloop feeppm parameter

- liquidity/autoloop_testcontext_test.go
Previously we would only check the mocked lnd channels for dispatched swaps against our **expected** swaps in the tests. If our expected swaps were `nil` we would never proceed with checking whether the channels had values ready to read or not.
This PR adds extra checks on the `autoloop` and `easyautoloop` step functions to also check for false-positive dispatched swaps.
> liquidity: add false-positive checks on autoloop tests

- release.sh
The modernc.org/sqlite package does not build on windows 386 so we're removing it from our release script.
> build: deprecate windows 386 from the release

- docs/autoloop.md
The main purpose of this pull request is to fix the `loop setrule --type={in|out}` command. H/t to @hieblmi for finding the error!
The pull request also standardizes some language and capitalization, including
- Capitalizing Loop In and Loop Out
- Capitalizing Autoloop
- Referring to Autoloop as Autoloop, rather then the autolooper
> Correct loop setrule command and styling in Autoloop guide

- loopd/migration.go
This commit ensures that we don't even check for the existence of the loop.db file if `loop_sqlite.db` already present. This is to ensure that on systems that may by any trigger restore deleted files we don't try to re-run migration which would otherwise make `loopd` unable to start up properly.
Fixes https://github.com/lightninglabs/loop/issues/626
> loopd: always skip migration if `loop_sqlite.db` file already exists

- liquidity/liquidity.go
This PR allows the auto loop-in dispatcher to continue with the execution of the next swap once a previous swap's invoice is settled. 
Set parameters
```
loop --network regtest setparams --autoloop=true --autobudget 10000000 --maxamt 1000000 --feepercent 20 --autoinflight 10
```
Set rule
```
loop --network regtest setrule --type in --outgoing_threshold 99 node_key_to_loop_in_to
```
Result:
A new swap is dispatched although the previous swap is still in a pending state
```
LOOP_IN SUCCESS 0.003 BTC - P2TR: bcrt1p7awp9kaujtdr5h2pzlcpzyuypjsnh35trv5ma49mznfkl6yntntsh739lh (cost: server 130, onchain 7700, offchain 0)
LOOP_IN INVOICE_SETTLED 0.003 BTC - P2TR: bcrt1para8f4fy3r9qtrvvpmrf0z3uzwh776zv7577fsx24k8mvtxfagrqhp6w87 (cost: server -299870, onchain 7700, offchain 0)
LOOP_IN HTLC_PUBLISHED …
```
> auto loopin: consider settled invoices swap succeeded

- sample-loopd.conf
Addresses https://github.com/lightninglabs/loop/issues/528
This PR introduces a sample configuration file for `loopd`. The configuration pattern follows the style which was introduced for `lnd`'s sample configuration file in https://github.com/lightningnetwork/lnd/pull/7770.
This PR was tested in regtest by outsourcing the following command line flags to the configuration file:
```
--network=regtest
--debuglevel=debug
--server.host=localhost:11009
--server.notls
--lnd.host=localhost:10011
--lnd.macaroonpath=.../docker/mounts/regtest/alice/admin.macaroon
--lnd.tlspath=.../docker/mounts/regtest/alice/tls.cert
```
> conf: sample config for loopd

- loopd/daemon.go
- loopd/migration.go
- loopd/utils.go
- loopd/view.go
In preparation of https://github.com/lightninglabs/loop/pull/642, this PR extracts the db opening into its own util function and exposes the `BaseDB` struct in the daemon.
> db: refactor db opening

- regtest/docker-compose.yml
This PR replaces https://github.com/lightninglabs/loop/pull/520 with latest versions.
> regtest: bump versions

- staticaddr/script/script.go
- staticaddr/script/script_test.go
- utils/musig.go
In this PR we introduce taproot scripting for static loop-in addresses.
> script: static address taproot script

- loopdb/sqlc/batch.sql.go
- loopdb/sqlc/querier.go
- loopdb/sqlc/queries/batch.sql
- loopin.go
- loopout.go
- sweepbatcher/store.go
- sweepbatcher/store_mock.go
- sweepbatcher/sweep_batch.go
- sweepbatcher/sweep_batcher.go
- sweepbatcher/sweep_batcher_test.go
This PR fixes how we calculate the on-chain cost when batching and also cleans up server cost calculation so it never gets negative or too large (due to addition of the swap amount).
> loop: fix the loopout per sweep onchain cost and cleanup server cost calculation (both loopin and loopout)

- Makefile
This PR speeds up local docker builds, similar to how its done in lnd: https://github.com/lightningnetwork/lnd/blob/master/Makefile#L66
To test I ran `make lint` twice, noticing a x2 improvement.
> Speed up docker runs

- sweepbatcher/sweep_batch.go
> sweepbatcher: add more debug logging

- loopd/daemon.go
> daemon: fix wrapped errors and typos

- fsm/example_fsm_test.go
- fsm/fsm.go
- fsm/observer.go
By adding WaitForStateAsync to the observer we can always observe state changes in an atomic way without relying on the observer's internal cache.
> fsm: add WaitForStateAsync to the cached observer

- loopout.go
- sweepbatcher/sweep_batch.go
- sweepbatcher/sweep_batcher_test.go
> loopout: fix negative reported fees

- sweepbatcher/log.go
- sweepbatcher/store.go
- sweepbatcher/sweep_batch.go
- sweepbatcher/sweep_batcher.go
- sweepbatcher/sweep_batcher_test.go
Avoid adding a sweep to two batches:
- existing in the first `for` loop,
- any other batch in the second `for`
If the sweep was successfully updated in the batch, no need to try to add it to all other batches. So `return` in the first loop in case of acceptance.
Added a test reproducing adding a sweep to both batches without this change.
Also fixed some long lines of code (>80 chars) in a separate commit.
This PR was moved from https://github.com/lightninglabs/loop/pull/755#discussion_r1614040088
> sweepbatcher: exit early in handleSweep

- loopout_test.go
- sweepbatcher/store_mock.go
- sweepbatcher/sweep_batch.go
- sweepbatcher/sweep_batcher.go
- sweepbatcher/sweep_batcher_test.go
- testcontext_test.go
After loading from DB the value of `batchConfTarget` used to be set to default (`defaultBatchConfTarget` = 12) which
could in theory affect the fee rate if `updateRbfRate()` and `publish()` were not called before the batch was saved. It was unlikely, but possible in theory. Also it was error-prone to have wrong value in that field, in case it was used for something in the future.
Constant `defaultBatchConfTarget` was removed, it is never used before is overwritten in any non-buggy scenario. Added a check that `batchConfTarget != 0` (if 0, `updateRbfRate` ~fails~ prints a warning).
Added a test checking that batch confTarget survives DB store-load cycle.
To do it, `StoreMock` was updated to attach `LoopOut` in `FetchBatchSweeps` method (otherwise `convertSweep` crashes). Now …
> sweepbatcher: load from DB preserves confTarget

- go.mod
- go.sum
- instantout/instantout.go
- liquidity/loopin.go
- loopin.go
- loopout_test.go
- swap/htlc.go
- sweep/sweeper.go
- sweepbatcher/sweep_batch.go
- tools/Dockerfile
This PR bumps the loop client to the latest stable `lnd` release `v0.18.0-beta`.
EDIT: And `lndclient` to `0.18.0-1` which also points to `lnd v0.18.0-beta`.
> gomod: bump lnd to version 0.18.0-beta

- loopdb/sqlc/batch.sql.go
- loopdb/sqlc/instantout.sql.go
- loopdb/sqlc/querier.go
- loopdb/sqlc/queries/batch.sql
- loopdb/sqlc/queries/instantout.sql
- loopdb/sqlc/queries/swaps.sql
- loopdb/sqlc/swaps.sql.go
- loopout_test.go
- sweepbatcher/store.go
- sweepbatcher/store_mock.go
- sweepbatcher/sweep_batcher.go
- sweepbatcher/sweep_batcher_test.go
- testcontext_test.go
Method `sweepbatcher.Store.GetBatchSweeps` used to provide data from tables outside of sweepbatcher: `swaps`, `loopout_swaps`, `htlc_keys`. It made it harder to reuse. `Batcher` already has a straightforward way to get swap data: `LoopOutFetcher` interface (`loopdb.FetchLoopOutSwap`).
In this PR I switch the Batcher to use `LoopOutFetcher` interface and to stop providing this data as part of `GetBatchSweeps` method in `Store` and `StoreMock`.
> sweepbatcher/Store: use only own tables (separating from loopdb)

- client.go
- loopout_test.go
- sweepbatcher/sweep_batcher.go
- sweepbatcher/sweep_batcher_test.go
- testcontext_test.go
Changed argument of function NewBatcher from LoopOutFetcher to SweepFetcher (returning new public type SweepInfo). This change is backwards-incompatible on the package layer, but nobody seems to use the package outside of Loop.
To use NewBatcher inside Loop, turn loopdb into SweepFetcher using function NewSweepFetcherFromSwapStore.
> sweepbatcher: factor out loopdb-less version

- client.go
- loopin.go
- utils.go
Minor refactoring to use `lndclient.LightningClient` instead of `lndclient.LndServices`.
> utils: refactor SelectHopHints to use narrower interface

- instantout/reservation/store.go
- instantout/store.go
- loopdb/sql_store.go
- loopdb/sqlite.go
- sweepbatcher/store.go
This fixes a crash on postgres, can be observed in this PR adding sweepbatcher tests with SQL backends: https://github.com/lightninglabs/loop/pull/778
For some reason sqlite works even without this fix. Maybe it ignore the read only flag on the transaction?
> sweepbatcher: use write tx in DropBatch

- instantout/reservation/manager_test.go
- instantout/reservation/store.go
- instantout/reservation/store_test.go
- instantout/store.go
- loopd/daemon.go
- loopd/view.go
- loopdb/sql_store.go
- loopdb/sqlite.go
- loopdb/typed_store.go
- sweepbatcher/store.go
Provide a wrapped store type, exposing `ExecTx` method with a subset interface in the callback argument. `BaseDB` interfaces in `instantout`, `reservation` and `sweepbatcher` use `ExecTx` with their subset `Querier` instead of whole `sqlc.Querier` (`*sqlc.Queries`).
This is needed to make the packages more reusable, so they don't depend on methods of `*sqlc.Queries` they don't use.
Also factor out interface Querier from BaseDB for use in ExecTx type casts.
> loopdb: parameterize ExecTx with subset of methods used by a package

- sweepbatcher/sweep_batcher.go
- sweepbatcher/sweep_batcher_test.go
This is needed to cover the code of SQLStore with tests.
To achieve compatibility with loopdb (SQLite), the following changes were done:
- DestAddr is filled to avoid crash in SQL layer
- Preimage is filled to avoid uniqueness checks by the DB
- the code working with batch IDs was changed to work correctly when batch_id starts with 1 instead of 0
- SQL swap store has to have a swap with swap_hash from sweep to satisfy foreign key constraint of the DB
> sweepbatcher: unit tests with SQL loopdb as well

- sweepbatcher/sweep_batch.go
- sweepbatcher/sweep_batcher.go
- sweepbatcher/sweep_batcher_test.go
It disables fee bumping. It is useful when fee rate is set externally.
Add test for fee bumping, testing both modes.
> sweepbatcher: add option WithNoBumping

- sweepbatcher/sweep_batch.go
- sweepbatcher/sweep_batcher.go
- sweepbatcher/sweep_batcher_test.go
MinFeeRate is minimum fee rate that must be used by a batch of the sweep. If it is specified, confTarget is ignored.
This is useful for external source of fees.
> sweepbatcher: add field SweepInfo.MinFeeRate 

- loopdb/sqlc/batch.sql.go
- loopdb/sqlc/queries/batch.sql
- sweepbatcher/store.go
- sweepbatcher/sweep_batcher.go
Previously, when handling a sweep we assumed that if a sweep status was completed, the parent batch was also finished. However, since the batch confirmation status depends on three on-chain confirmations, it is possible that a spend notifier was started for a sweep of an active batch. The notifier would fetch the parent batch from the database, but because we incorrectly assumed that  the parent was confirmed (when it was not), the DB call would fail with a 'no rows returned' error. This failure would cause the sweep to fail and the sweep batcher to stop, resulting in a permanent failure state.
> sweepbatcher: fix spawning condition "unattached" spend notifiers

- instantout/store.go
Minor fix to instantiate the instantout sql store with network params.
> instantout: assign chaincfg in sql store

- loopout_test.go
- sweep/sweeper.go
- sweepbatcher/greedy_batch_selection.go
- sweepbatcher/greedy_batch_selection_test.go
- sweepbatcher/sweep_batch.go
- sweepbatcher/sweep_batcher.go
- sweepbatcher/sweep_batcher_test.go
New algorithm is tried to select a batch to add a sweep to. It selects a batch for the sweep using the greedy algorithm, which minimizes costs, and adds the sweep to the batch or creates new batch, if it is the most cost efficient alternative. If the batch does not accept the sweep (too long timeout distance), next batch is tried. If the whole new approach fails, the old algorithm is used, trying to add to any batch, or starting a new batch.
The PR also includes some refactorings and fixes small inaccuracies in fee estimations.
> sweepbatcher: add greedy batch selection algorithm

- client.go
- client_test.go
- testcontext_test.go
Loop used to "forget" last_hop of swaps created before its restart. The commit fixes this.
Added test TestFetchSwapsLastHop for this. Filled field abandonChans in test utility function newSwapClient because the field is used in new test.
Fixes https://github.com/lightninglabs/loop/issues/798
> client: fill LastHop in FetchSwaps

- swap/htlc.go
- sweepbatcher/greedy_batch_selection_test.go
According to `AddTapscriptInput`'s godoc, the first argument (`leafWitnessSize`) must include not the whole size of witness, but only the size of data consumed by the revealed script. Previously the value was too high, because it also included the following extra elements: number_of_witness_elements (1 byte), witness script and its size, control block and its size.
Tests for greedy_batch_selection were affected by this change.
Factored out from https://github.com/lightninglabs/loop/pull/791
> swap: fix leaf estimation in AddSuccessToEstimator

- sweepbatcher/store.go
- sweepbatcher/sweep_batch.go
- sweepbatcher/sweep_batcher.go
- sweepbatcher/sweep_batcher_test.go
- test/timeout.go
**WithInitialDelay** instructs sweepbatcher to wait for the duration provided after new batch creation before it is first published. This facilitates better grouping. It only affects newly created batches, not batches loaded from DB, so publishing does happen in case of a daemon restart (especially important in case of a crashloop). Defaults to 0s. If a sweep is about to expire (time until timeout is less that 2x initialDelay), then waiting is skipped.
**WithPublishDelay** sets the delay of batch publishing that is applied in the beginning, after the appearance of a new block in the network or after the end of initial delay (see WithInitialDelay). It is needed to prevent unnecessary transaction publishments when a spend is detected on that block. Default value depends on the network: 5 …
> sweepbatcher: add options WithInitialDelay and WithPublishDelay

- sweepbatcher/greedy_batch_selection.go
- sweepbatcher/greedy_batch_selection_test.go
- sweepbatcher/sweep_batch.go
- sweepbatcher/sweep_batcher.go
- sweepbatcher/sweep_batcher_test.go
- test/signer_mock.go
Option `WithMixedBatch` instructs `sweepbatcher` to create mixed batches with regard to cooperativeness. Such a batch can include both sweeps signed both cooperatively and non-cooperatively. If cooperative signing fails for a sweep, transaction is updated to sign that sweep non-cooperatively and another round of cooperative signing runs on the remaining sweeps. The remaining sweeps are signed in non-cooperative (more expensive) way. If the whole procedure fails for whatever reason, the batch is signed non-cooperatively (the fallback).
Updated greedy batch selection algorithm to take into account whether mixed batches are enabled.
> sweepbatcher: add mixed batches as an option

- sweepbatcher/greedy_batch_selection.go
- sweepbatcher/sweep_batch.go
- sweepbatcher/sweep_batcher_test.go
This is needed to avoid non-standard batch transactions (larger than 400k wu). A non-cooperative input is 393 wu, so 1000 inputs are still under 400k wu.
> sweepbatcher: set max batch size to 1000 sweeps

- sweepbatcher/sweep_batch.go
Fix log message. In current `master` branch it is like this:
```
Skipping publishing, because thebatch is not open (1).
```
> sweepbatcher: fix typo in log message

- sweepbatcher/sweep_batch.go
> sweepbatcher: log confirmed batch tx id

- test/chainnotifier_mock.go
- test/invoices_mock.go
- test/signer_mock.go
- test/versioner_mock.go
- test/walletkit_mock.go
Updating the mocks to be complete implementation of the underlying interfaces is not always possible due to cross dependency issues. This commit embeds the interfaces into the mocks so we can at least always compile them.
> test: support incomplete mocks

- sweepbatcher/sweep_batch.go
- sweepbatcher/sweep_batcher_test.go
Previous behaviour was to overwrite batch's feerate with minFeeRate of its primary sweep, which could be lower that previus batch's feerate or lower that feerate of some other sweep.
Instead, batch's feerate only grows and never declines and is at least as high as the highest feerate of its sweeps.
Added a test to verify this.
> sweepbatcher: make sure feerate does not decrease

- client.go
- liquidity/liquidity.go
- loopd/log.go
- loopin.go
- loopin_test.go
- loopout.go
- loopout_feerate.go
- loopout_feerate_test.go
- sweep/log.go
- sweep/sweeper.go
Add type `loopOutSweepFeerateProvider` which determines confTarget based on distance to swap expiration, then determines feerate and fee using. Fee rate is plugged into sweepbatcher using `WithCustomFeeRate`. Option WithPublishDelay is used to make sure fee-rate is updated by loopout.go before the value is used by sweepbatcher.
When determining confTarget, there are few adjustments over raw distance to cltv_expiry:
- make sure confTarget is positive (if the swap has expired, raw distance is negative)
- If confTarget is less than or equal to `DefaultSweepConfTargetDelta` (10), cap it with `urgentSweepConfTarget` and apply fee factor (1.1x).
Also, if feerate is less than floor (1 sat/vbyte), then the floor is used.
`DefaultSweepConfTargetDelta` was decreased from 18 to 10.
Every block 100 …
> loopout: re-target sweep's feerate every block

- loopd/log.go
- loopd/run.go
Just a short drive-bug fix: loopd crashes when you wanna show the logging subsystems with `loopd --debuglevel show`
This fix just copies the rogue code to another place, but I think a better fix would be to get rid of the global pointer and maybe just return the logger when setting it up ?
> loopd: nil-pointer bug when showing subsystems

- loopd/config.go
- loopd/daemon.go
- sample-loopd.conf
This PR adds signet support for the loop client.
This PR is in draft until instance `signet.swap.lightning.today:11010` is up and running
> Signet support

- loopd/daemon.go
- loopdb/sqlc/migrations/000009_static_address.up.sql
- loopdb/sqlc/models.go
- loopdb/sqlc/queries/static_addresses.sql
- loopdb/sqlc/static_addresses.sql.go
- staticaddr/address/interface.go
- staticaddr/address/manager.go
- staticaddr/address/manager_test.go
- staticaddr/address/sql_store.go
- staticaddr/deposit/manager.go
The height hint for deposit confirmations was previously set to the initiation height of the deposit manager, which does not work in case the manager is restarted before a deposit was confirmed.
> StaticAddr: fix deposit detection

- cmd/loop/staticaddr.go
- loopd/daemon.go
- staticaddr/withdraw/manager.go
Gather PR to fix upcoming rc testing issues.
- checks dust limits before withdrawing deposits
- removes the `--experimental` flag for static addresses
- fixes text formatting
> StaticAddr: fix rc review comments

- loopout.go
Original message "Checking preimage reveal height 231435 exceeded" was not clear and could be interpreted that the swap has expired. Now the same message looks like this: "Checking if preimage reveal height 231435 was exceeded".
> loopout: improve log messages

- notifications/manager.go
- notifications/manager_test.go
> notifications: implement incremental backoff for invalid L402 tokens

- notifications/manager.go
> notifications: do not hog the CPU if there's no L402 token yet

- .github/workflows/main.yml
The setup-go@v5 has built in caching support (introduced in https://github.com/actions/setup-go?tab=readme-ov-file#v4).
> github: update `setup-go` remove `cache`

- staticaddr/loopin/actions.go
- staticaddr/loopin/manager.go
Ensure that MuSig2 cleanup does happen even if a context expires.
> loopin: use context.WithoutCancel in cleanup

- loopout_feerate.go
- loopout_feerate_test.go
The fee estimator fails if conf_target=1. Use conf_target=2 instead.
Fix https://github.com/lightninglabs/loop/issues/898
> loopout: fix fee estimate failure if conf_target=1

- looprpc/go.mod
- staticaddr/deposit/actions.go
- staticaddr/deposit/fsm.go
- staticaddr/deposit/manager.go
Fixes race conditions in the static address withdrawal manager.
> staticaddr: lock mutex for active deposits access

- staticaddr/deposit/manager.go
Previously the deposit recovery took place in a goroutine per deposit. Since the withdrawal manager recovery depends on a completed deposits recovery, this PR removes the goroutine around the deposits recovery to block until all deposits are fully recovered.
> staticaddr: non-concurrent deposit recovery

- regtest/README.md
- regtest/docker-compose.yml
- regtest/regtest.sh
New loop features like instant loop-out and static loop-in depend on aperture.
This PR adds a aperture docker instance to allow the loop client to acquire a L402 which is precondition for the instant and static service.
> regtest: adding aperture docker instance

- loopdb/postgres.go
- loopdb/sqlc/batch.sql.go
- loopdb/sqlc/migrations/000013_batcher_key_outpoint.down.sql
- loopdb/sqlc/migrations/000013_batcher_key_outpoint.up.sql
- loopdb/sqlc/models.go
- loopdb/sqlc/querier.go
- loopdb/sqlc/queries/batch.sql
- sweepbatcher/greedy_batch_selection.go
- sweepbatcher/greedy_batch_selection_test.go
- sweepbatcher/store.go
- sweepbatcher/store_mock.go
- sweepbatcher/sweep_batch.go
- sweepbatcher/sweep_batcher.go
- sweepbatcher/sweep_batcher_test.go
SwapHash used to be a key in the sweeps table. Now the key is `outpoint` which replaces columns `outpoint_txid` and `outpoint_index`. In-memory structures and unit tests were also updated to use outpoint as key. Outpoint is truly unique.
**DB migration**: this PR involves a DB migration. Table `sweeps` is recreated to make column `swap_hash` non-unique and to create column `outpoint` from columns `outpoint_txid` and `outpoint_index`. Column `outpoint_txid` is byte-reversed and converted to HEX. I tested the migration manually on both postgres and sqlite.
> sweepbatcher: allow swap_hash to be non-unique

- cmd/loop/main.go
Adds ability to global flags to de config using ENV variables.
This is useful when running `loop` in containers and for any reason not using default values or running lightning-terminal in integrated mode.
> loop: Global flags to accept ENV vars overrides.

- sweepbatcher/sweep_batch.go
- sweepbatcher/sweep_batcher.go
- sweepbatcher/sweep_batcher_test.go
Option `WithInitialDelay` now accepts a function returning initialDelay depending on sweep's data.
This is needed to be able to wait longer for sweeps with low priority, but still sweeping high priority sweeps soon.
>  sweepbatcher: customize initialDelay per sweep

- loopout.go
- sweepbatcher/greedy_batch_selection.go
- sweepbatcher/greedy_batch_selection_test.go
- sweepbatcher/sweep_batch.go
- sweepbatcher/sweep_batcher.go
- sweepbatcher/sweep_batcher_test.go
A group of inputs can be added by passing it in `SweepRequest.Inputs` field.
All the inputs belong to the same swap and are added to the same batch.
> sweepbatcher: allow adding groups of inputs

- loopdb/sqlc/migrations/000013_batcher_key_outpoint.up.sql
Don't copy values of ID column from sweeps to sweeps2 and let it auto-assign values there. This is needed for the sequencer for that column to be up-to-date with the values.
I manually tested the migration in sqlite3 and postgres.
> loopdb: fix migration 13 for Postgres

- cmd/loop/liquidity.go
- cmd/loop/loopin.go
- cmd/loop/loopout.go
Verify the number of positional arguments if they were provided to crash in such scenarios:
```
$ loop out 250000 --xxx
$ loop in 250000 1000
```
These commands used to work ignoring the last argument.
> cmd/loop: crash if unknown flags are provided

- sweepbatcher/sweep_batch.go
- sweepbatcher/sweep_batcher_test.go
Previously, we passed the current best block height as the height hint to `RegisterConfirmationsNtfn`. If Loop was shut down when a sweep was confirmed and restarted later, it would use the current best height as the hint. This caused the confirmation to be missed, since it had already occurred before that height.
This commit fixes the issue by passing the initiation height of the swap as the height hint instead. This is consistent with what we do in other places where we use `RegisterConfirmationsNtfn`.
Since LND caches previously passed height hints for RegisterConfirmationsNtfn and uses maximum passed value, to actually recover in such a condition, one has to restart LND passing the option `--height-hint-cache-query-disable` and then restart Loop applying this fix. If a pruned bitcoind …
> sweepbatcher: fix height hint for confirmations

- staticaddr/deposit/fsm.go
- staticaddr/withdraw/manager.go
This PR adds the ability to request signatures for higher fee versions of previously published withdrawal transactions.
> staticaddr: allow rbf'ing withdrawal transactions

- loopout.go
- sweepbatcher/log.go
- sweepbatcher/presigned.go
- sweepbatcher/presigned_test.go
- sweepbatcher/store_mock.go
- sweepbatcher/sweep_batch.go
- sweepbatcher/sweep_batch_test.go
- sweepbatcher/sweep_batcher.go
- sweepbatcher/sweep_batcher_presigned_test.go
- sweepbatcher/sweep_batcher_test.go
- test/lnd_services_mock.go
- test/walletkit_mock.go
In this mode sweepbatcher uses transactions provided by the Presigned helper.
Transactions are signed upon adding an input to a batch.
A single Batcher instance can handle both presigned and regular batches.
Currently presigned and non-presigned sweeps never appear in the same batch.
> sweepbatcher: add mode with presigned transactions

- staticaddr/loopin/manager.go
If the notification manager shuts down, sweepReqs channel is closed and sweepReq object received from it becomes nil, causing panic in handleLoopInSweepReq. Now this is fixed by checking if the channel was closed and if it was shutting down loop-in manager itself.
> staticaddr: fix crash in loop-in manager shutdown

- cmd/loop/staticaddr.go
Fixes static address command descriptions.
> cmd: fix command descriptions

- Makefile
- loopd/swapclient_server.go
- looprpc/client.pb.go
- looprpc/client.proto
- looprpc/client.swagger.json
- release_notes.md
- version.go
This PR updates the `GetInfo` response to adhere to https://github.com/lightninglabs/lightning-terminal/pull/1034.
In general it updates the output of the `commit_hash` field in the GetInfoResponse.
The `commit_hash` field will now contain the most recent commit_hash that the build was based on. If the build had uncommitted changes, this field will contain the most recent commit hash, suffixed by "-dirty".
We also change the output of `commit` field in the `--version` command. The `Commit` field will now contain most recent git commit tag.
Note that both of these changes are breaking changes!
Additionally we also add a `commit_hash` part of the output of the `--version` output.
> Update commit_hash field to GetInfo response

- loopd/daemon.go
- staticaddr/address/manager.go
- staticaddr/address/manager_test.go
- staticaddr/deposit/manager.go
- staticaddr/deposit/manager_test.go
- staticaddr/loopin/manager.go
- staticaddr/withdraw/manager.go
This PR reverts a regression that was introduced in 042fe9f3253601fa2093abcbb2c3b42c76d6eb66 by making sure that the address manager is initialized before other managers begin their initialization.
It also applies the init pattern of reservations to staticaddr-managers.
> staticaddr: wait for address manager initiation

- release.sh
A commit_hash component was added to the version string:
```
loop version 0.31.2-beta commit=v0.31.2-beta-dirty commit_hash=xxx
```
As `.*` is greedy, it captured "0.31.2-beta commit=v0.31.2-beta-dirty" instead of just "0.31.2-beta".
This commit fixes this.
> release.sh: fix version matching

- loopdb/sqlc/batch.sql.go
- loopdb/sqlc/querier.go
- loopdb/sqlc/queries/batch.sql
- loopout.go
- loopout_feerate.go
- sweepbatcher/presigned.go
- sweepbatcher/presigned_test.go
- sweepbatcher/store.go
- sweepbatcher/store_mock.go
- sweepbatcher/sweep_batch.go
- sweepbatcher/sweep_batcher.go
- sweepbatcher/sweep_batcher_presigned_test.go
- sweepbatcher/sweep_batcher_test.go
- test/chainnotifier_mock.go
Fixed TODO left from https://github.com/lightninglabs/loop/pull/891 : re-add sweeps to new batches only after fully confirmed.
In case of a reorg sweeps should not go to another batch but stay in the current batch until it is fully confirmed. Only after that the remaining sweeps are re-added to another batch. Field `sweep.completed` is now set to true only for fully-confirmed sweeps.
Fixed OnChainFeePortion values. There were two mistakes. In case of a swap with multiple sweeps only the fee of the first sweep of a swap was accounted. Another issue is that  rounding diff (the remainder) was attributed to all the sweeps rather than to the first (primary) sweep of the batch. The sweep to attribute the remainder was chosen by comparing SignatureScript which is 
always empty. New approach is …
> sweepbatcher: fixes for presigned mode

- staticaddr/deposit/fsm.go
- staticaddr/withdraw/manager.go
Previously upon recovery, a withdrawing deposit was
first transitioned into the Deposited state by the
deposit manager, and then again into the Withdrawing
state by the withdrawal manager. The first transition
is unnecessary, so we just remain in the Withdrawing
state upon recovery.
> staticaddr: simplify withdrawal fsm transition

- Makefile
- release.sh
Make `loop` and `loopd` binaries static, more portable.
Binaries built with dynamic dependencies can't be freely moved across machines with different distributions (e.g. NixOS -> Debian breaks because it can't find some libraries).
> make: set CGO_ENABLED=0

- go.mod
- loopout.go
- sweepbatcher/sweep_batch.go
- sweepbatcher/sweep_batcher.go
- sweepbatcher/sweep_batcher_test.go
- test/chainnotifier_mock.go
- test/lightning_client_mock.go
- test/router_mock.go
The reorg channel is now passed to `RegisterSpendNtfn`, and waiting for spend notifications remains active even after the transaction receives its first confirmation. The dedicated goroutine previously used to wait for the spend is no longer needed, as we now handle both spend and potential reorg events in the main event loop while the batch is running.
Following this change, `RegisterConfirmationsNtfn` runs without a reorg channel, as it would only detect deep reorgs that undo the final confirmation - something we can't handle anyway. We can't track fully confirmed swaps indefinitely to guard against such rare reorgs; instead, we can mitigate the risk by increasing the required confirmation depth.
Also changed sweepbatcher to update feerate independently of `AddSweep` as well. `AddSweep` …
> sweepbatcher: fix reorg detection

- loopout_test.go
- sweepbatcher/greedy_batch_selection.go
- sweepbatcher/greedy_batch_selection_test.go
- sweepbatcher/presigned.go
- sweepbatcher/presigned_test.go
- sweepbatcher/sweep_batch.go
- sweepbatcher/sweep_batch_test.go
- sweepbatcher/sweep_batcher.go
- sweepbatcher/sweep_batcher_presigned_test.go
- sweepbatcher/sweep_batcher_test.go
- utils/dust_limit.go
- utils/dust_limit_test.go
- utils/tx_sort.go
The batcher receives the ability to sign and publish batches with change outputs.
Change is created when the clients choose fractional swap amounts from the input values to be swapped. Usually the change is sent back to client's addresses.
If change is provided to `ensurePresigned`, `presign` and `publishPresigned`, it is expected to be placed within the passed `[]sweep`.
Each `sweep` optionally holds a pointer to a change output. Only the first sweep in a sweep group called primary deposit will hold a pointer to the respective swap's change output.
> sweepbatcher: batch change outputs

- staticaddr/withdraw/manager.go
`lnd v0.19.2-beta` introduced `chainfee.FeeForWeightRoundUp` which helps us fix https://github.com/lightninglabs/loop/issues/966.
> fee: round up transaction weight to the nearest satoshi

- loopd/swapclient_server.go
- loopd/swapclient_server_test.go
- test/lnd_services_mock.go
- test/walletkit_mock.go
_fixes https://github.com/lightninglabs/loop/issues/992_
ListUnspentRaw returns the unspent wallet view of the
backing lnd wallet. It might be that deposits show up
there that are actually not spendable because they
already have been used but not yet spent by the server.
We filter out such deposits in ListUnspentDeposits.
> staticaddr: filter unavailable deposits in `ListUnspentDeposits`

- AGENTS.md
- README.md
- docs/architecture.md
My experiment of using Gemini in Loop code base.
I asked Gemini to read the whole project and to save the context to AGENTS.md. This file is picked up by such tools automatically so it may help with further AI application as they will know what is stored where.
I noticed that README.md and architecture.md were outdated and tried to update them using the same tool. The committed version includes my manual edits, since it didn't understand originally how onchain HTLCs work.
> Updated README and architecture.md with Gemini, added AGENTS.md

- loopd/swapclient_server.go
- staticaddr/deposit/manager.go
- staticaddr/deposit/sql_store.go
- staticaddr/loopin/interface.go
- staticaddr/loopin/manager.go
- staticaddr/loopin/manager_test.go
When the client evaluates signature requests for batches that include multiple unrelated inputs the client should ignore those when checking for correct change.
> staticaddr: ignoreUnknown flag for DepositsForOutpoints

- sweepbatcher/sweep_batcher_presigned_test.go
The test `TestPresigned/dust_main_output` was causing a deadlock. When the test called `batcher.AddSweep` for the second time (with a valid sweep), the batcher would create a new batch and attempt to register for a spend notification. However, the test was not waiting for or consuming this notification registration, leading to a blocked goroutine and a timeout.
I have added a line to the test to consume the spend notification registration from the mock lnd's channel, similar to how other tests in the same file are structured. This prevents the deadlock.
The problem was introduced in commit 54652dc6415cf202993f73a9224a6fbbb2dd4fcc.
https://github.com/lightninglabs/loop/actions/runs/18077891523/job/51437024222?pr=1007
```
=== RUN   TestPresigned/dust_main_output
2025-09-28 18:17:14.123 …
```
> sweepbatcher: fix flacky TestPresigned/dust_main_output

- Makefile
- README.md
- docs/release.md
- release.Dockerfile
- release.sh
This pull request introduces a new `make docker-release` target to enable reproducible builds of Loop releases. The goal is to ensure that anyone can build the same binaries from the same source code.
*   **Reproducible Builds:**
*   The `release.sh` script has been updated to produce reproducible artifacts. This includes:
*   Building Go in a reproducible way.
*   Creating reproducible `.zip` and `.tar.gz` archives.
*   Ensuring the list of tags in the manifest is reproducible.
*   The script now clones the repository before building to ensure a clean build environment.
*   **`docker-release` Target:**
*   A new `docker-release` target has been added to the `Makefile`.
*   This target uses a Docker container to build the release, ensuring a consistent build environment across different …
> Docker release

- sweepbatcher/sweep_batcher.go
- sweepbatcher/sweep_batcher_test.go
Re-ordered the cleanup in handleSweeps so completed batches are deleted only after any re-add attempt, preventing a finished batch from being dropped before it can absorb the re-add.
Added a fresh status/parent-batch lookup inside handleSweeps so the logic now reacts to swaps that complete between AddSweep and the event-loop handler; fully confirmed sweeps are routed straight to monitorSpendAndNotify instead of spawning a duplicate batch.
Added regression test testSweepBatcherHandleSweepRace, which replays the AddSweep/confirmation race and verifies that only the original batch remains and the sweep keeps its parent assignment.
> sweepbatcher: harden AddSweep race handling
